# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.TextField(default='Normal Message', verbose_name='command status'),
        ),
    ]
