# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(default='Normal Message', null=True, verbose_name='command status'),
        ),
    ]
